from django.forms import ModelForm
from .models import Account#, LoginModel
from django import forms

# Create the form class.
'''NOTE: forms are included in views to be rendered.
		the fields in each form include what inputs to render
'''

class Register(ModelForm):
	class Meta:
		model = Account
		#user_id is autogenerated so no need to render its input field in this form
		fields = ['username', 'email','password']


class Login(ModelForm):
	class Meta:
		model = Account
		fields = ['username', 'password']
