from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .forms import Register
from .models import Account

# Create your views here.

#region Helper functions
from hashlib import sha256

# def getJWToken():
# 	redirect('token_obtain_pair')
def hashPassword(plain):
    return sha256(plain.rstrip().encode()).hexdigest()
#endregion


def index(request):
	return render(request,'index.html')

def HomePage(request):
	return render(request, 'HomePage.html')

def register(request):
	if request.method == 'POST':
		form = Register(request.POST)
		if form.is_valid():
			userform = form.cleaned_data
			# userid = userform['user_id'] #autogenerated
			username = userform['username']
			email = userform['email']
			password = hashPassword(userform['password'])
			Account.objects.create(username=username, email=email, password=password)
			
			#Render on page (Not needed for API)
			S=Account.objects.all()
			# print("type of S:",type(S))
			# getJWToken()
			#Not run:
			return render(request, 'register.html', {'form': form,'S':S})
	else:
		form = Register()
	S=Account.objects.all()
	# print("type of S:",type(S))
	return render(request, 'register.html', {'form': form,'S':S})

