# Generated by Django 3.0.4 on 2021-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
