# Generated by Django 3.1.7 on 2021-04-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20210413_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
    ]
