# Generated by Django 3.2 on 2021-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='canceled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
