# Generated by Django 3.2 on 2021-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_surgeries',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
