# Generated by Django 3.2 on 2021-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20210426_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='None', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_medications',
            field=models.CharField(default='None', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previous_surgeries',
            field=models.CharField(default='None', max_length=500, null=True),
        ),
    ]
