# Generated by Django 3.2 on 2021-04-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20210425_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
