# Generated by Django 3.0.4 on 2021-04-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
